app = "agora-lvao3a"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "agora_data"
  destination = "/app/data"
  initial_size = "1gb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true

[deploy]
  strategy = "rolling"
  max_unavailable = 1
  wait_timeout = "10m"

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"
